### ISSUE TITLE
demo site not serving

### ISSUE THREAD

**Issue by Dorifer** [jekyll-octopod/jekyll-octopod#42] opened 2017-11-29 09:09 UTC
trying to set up a new octopod project after octopod setup I try to run octopod serve and get the following error:
`WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
      rack (~> 1.5)
      tilt (< 3, >= 1.3)
      backports (>= 2.0)
      rack-test (>= 0)
      multi_json (>= 0)
      rb-inotify (>= 0.9, >= 0.9.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /home/dorifer/jekyll_projects/dopcast/_config.yml
Configuration file: /home/dorifer/jekyll_projects/dopcast/_config.yml
            Source: /home/dorifer/jekyll_projects/dopcast
       Destination: /home/dorifer/jekyll_projects/dopcast/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: undefined method `[]' for nil:NilClass in /_layouts/with_twitter_card.html
jekyll 3.4.3 | Error:  undefined method `[]' for nil:NilClass`

I'm on arch linux with ruby 2.4.2p198 and gem 2.6.13

**Comment by haslinger** [comment] 2017-11-29 09:21
Maybe it's the old Jekyll version, that's causing the issue. I'm currently using: jekyll 3.6.2
Please try in your Gemfile: 
`gem 'jekyll', "~> 3.6.0"`
P.S. Maybe it's also a good idea, to fix the jekyll version to the old one in existing running projects... Jekyll versions currently breaks things left and right ;-(

**Comment by cgascoig** [comment] 2017-12-21 06:48
I had the same issue on a fresh install of octopod using Jekyll 3.6.2. The issue seems to be that the with_twitter_card.html layout calls `{{ page.audio | audio }}` but the Jekyll sample post DATE-welcome-to-jekyll.markdown doesn't have an `audio` attribute in the front-matter. Removing the Jekyll sample post gets rid of the issue but I would expect the octopod filter to handle this scenario more gracefully.

**Comment by xtaran** [comment] 2017-12-30 17:32
Same here. "Solved" it by safeguarding `hsh[…]` accesses with this code: 

```
if hsh.nil?
  "Test"
else
  …
end
```

I was actually expecting to see that `Test` somewhere in the backtrace, but to my surprise it started up without error afterwards. On a first glance I even didn't find that `Test` anywhere in the demo posting's text or links. (Didn't check the source code of the page, though.)

Happened on Gentoo Linux with Jekyll 3.6.2.

**Comment by haslinger** [comment] 2018-03-20 11:04
Duplicate of #39 
-> Is now fixed by merging the pr from @marksweiss in master.
-> Will hopefully create a new release next week (have to update some docs before)  and then close this issue here

**Comment by haslinger** [comment] 2018-03-20 11:31
Well no ;-) The changes in the docs are unrelated, so new version created and published: 0.9.4.

**Closed as completed by haslinger** 2018-03-20 11:31 UTC
